FROM ubuntu:16.04

LABEL maintainer="Michael Bradley <michaelsbradleyjr@gmail.com>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y && \
    apt-get install -y wget && \
    wget -O netselect.deb http://http.us.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-28+b1_`dpkg --print-architecture`.deb && \
    dpkg -i netselect.deb && \
    rm netselect.deb && \
    rm -rf /var/lib/apt/lists/*
