#!/usr/bin/env bash
set -x #echo on

if [[ -d /home/python3/app/conf ]]; then
    if [[ ! -z "$(ls /home/python3/app/conf)" ]]; then
        ln -f -s /home/python3/app/conf/* -t /home/python3/conf        
     fi
fi
if [[ -d /home/python3/app/supervisor ]]; then
    if [[ ! -z "$(ls /home/python3/app/supervisor)" ]]; then
        ln -f -s /home/python3/app/supervisor/* -t /home/python3/conf/supervisor
    fi
fi

exec /home/python3/start0.sh
